### ISSUE TITLE
Application does not start when clicking it

### ISSUE THREAD

**Issue by LongJohn-Silver** [stanford-oval/almond-gnome#78] opened 2020-06-26 02:24 UTC
I'm on ElementaryOS Hera, and I'm running the Flathub version installed from the native application store, and when I click to open it, it does nothing. I don't know how to give you more information regarding the crash, but if there's a log somewhere that I can retrieve, I can find it a paste it here.

**Comment by gcampax** [comment] 2020-06-26 03:21
Can you run `journalctl -f` in the terminal and then try to start the application? That should show logs that might be related to why the app is not starting.
(Trim the logs before posting anything here, to avoid disclosing any sensitive info)

**Comment by LongJohn-Silver** [comment] 2020-06-26 14:31
jun 26 11:09:19  dbus-daemon[1240]: [session uid=1000 pid=1240] Activating service name='edu.stanford.Almond' requested by ':1.40' (uid=1000 pid=1543 comm="wingpanel " label="unconfined")
jun 26 11:09:19  systemd[1211]: Started flatpak-edu.stanford.Almond-2484.scope.
jun 26 11:09:20  dbus-daemon[1240]: [session uid=1000 pid=1240] Activating service name='edu.stanford.Almond.BackgroundService' requested by ':1.75' (uid=1000 pid=2489 comm="/usr/libexec/flatpak-dbus-proxy --args=35 " label="unconfined")
jun 26 11:09:20  systemd[1211]: Started flatpak-edu.stanford.Almond-2502.scope.
jun 26 11:09:21  edu.stanford.Almond.BackgroundService[1240]: ThingEngine-GNOME starting up...
jun 26 11:09:24  edu.stanford.Almond.BackgroundService[1240]: Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
jun 26 11:09:26  dbus-daemon[1240]: [session uid=1000 pid=1240] Activating via systemd: service name='org.freedesktop.portal.Desktop' unit='xdg-desktop-portal.service' requested by ':1.77' (uid=1000 pid=2507 comm="/usr/libexec/flatpak-dbus-proxy --args=35 " label="unconfined")
jun 26 11:09:26  systemd[1211]: Starting Portal service...
jun 26 11:09:26  dbus-daemon[1240]: [session uid=1000 pid=1240] Activating via systemd: service name='org.freedesktop.impl.portal.desktop.gtk' unit='xdg-desktop-portal-gtk.service' requested by ':1.79' (uid=1000 pid=2525 comm="/usr/libexec/xdg-desktop-portal " label="unconfined")
jun 26 11:09:26  systemd[1211]: Starting Portal service (GTK+/GNOME implementation)...
jun 26 11:09:26  dbus-daemon[1240]: [session uid=1000 pid=1240] Successfully activated service 'org.freedesktop.impl.portal.desktop.gtk'
jun 26 11:09:26  systemd[1211]: Started Portal service (GTK+/GNOME implementation).
jun 26 11:09:26  dbus-daemon[1240]: [session uid=1000 pid=1240] Successfully activated service 'org.freedesktop.portal.Desktop'
jun 26 11:09:26  systemd[1211]: Started Portal service.
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]: /app/lib/edu.stanford.Almond/service/main.js:13
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]: process.on('unhandledRejection', (up) => { throw up; });
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:                                            ^
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]: Error: No such interface found
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at /app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/introspect.js:31:23
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at Parser.<anonymous> (/app/lib/edu.stanford.Almond/service/node_modules/xml2js/lib/parser.js:304:18)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at Parser.emit (events.js:198:13)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at SAXParser.onclosetag (/app/lib/edu.stanford.Almond/service/node_modules/xml2js/lib/parser.js:262:26)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at emit (/app/lib/edu.stanford.Almond/service/node_modules/sax/lib/sax.js:624:35)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at emitNode (/app/lib/edu.stanford.Almond/service/node_modules/sax/lib/sax.js:629:5)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at closeTag (/app/lib/edu.stanford.Almond/service/node_modules/sax/lib/sax.js:889:7)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at SAXParser.write (/app/lib/edu.stanford.Almond/service/node_modules/sax/lib/sax.js:1436:13)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at Parser.exports.Parser.Parser.parseString (/app/lib/edu.stanford.Almond/service/node_modules/xml2js/lib/parser.js:323:31)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at Parser.parseString (/app/lib/edu.stanford.Almond/service/node_modules/xml2js/lib/parser.js:5:59)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at Object.module.exports.processXML (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/introspect.js:19:10)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at Object.<anonymous> (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/introspect.js:12:41)
jun 26 11:09:26  edu.stanford.Almond.BackgroundService[1240]:     at EventEmitter.<anonymous> (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/bus.js:138:19)
jun 26 11:09:26 user-MS-7A15 edu.stanford.Almond.BackgroundService[1240]:     at EventEmitter.emit (events.js:198:13)
jun 26 11:09:26 user-MS-7A15 edu.stanford.Almond.BackgroundService[1240]:     at /app/lib/edu.stanford.Almond/service/node_modules/dbus-native/index.js:106:14
jun 26 11:09:26 user-MS-7A15 edu.stanford.Almond.BackgroundService[1240]:     at Socket.<anonymous> (/app/lib/edu.stanford.Almond/service/node_modules/dbus-native/lib/message.js:55:9)
jun 26 11:09:26  dbus-daemon[1240]: [session uid=1000 pid=1240] Activated service 'edu.stanford.Almond.BackgroundService' failed: Process edu.stanford.Almond.BackgroundService exited with status 1
jun 26 11:09:26  edu.stanford.Al[2492]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process edu.stanford.Almond.BackgroundService exited with status 1
                                                    spawnServiceDBusActivation@resource:///edu/stanford/Almond/js/app/servicelaunch.js:47:9
                                                    spawnService@resource:///edu/stanford/Almond/js/app/servicelaunch.js:73:9
                                                    main@resource:///edu/stanford/Almond/js/app/main.js:114:21
                                                    run@resource:///org/gnome/gjs/modules/package.js:222:12
                                                    @/app/bin/edu.stanford.Almond:6:1
jun 26 11:09:26  edu.stanford.Almond[1240]: Script /app/bin/edu.stanford.Almond threw an exception
jun 26 11:09:27  dbus-daemon[1240]: [session uid=1000 pid=1240] Activated service 'edu.stanford.Almond' failed: Process edu.stanford.Almond exited with status 1
jun 26 11:09:56  xdg-desktop-por[2525]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list
jun 26 11:12:13  systemd[1]: Starting Cleanup of Temporary Directories...
jun 26 11:12:14  systemd[1]: Started Cleanup of Temporary Directories.

**Comment by LongJohn-Silver** [comment] 2020-06-26 14:31
Was that good enough?

**Comment by gcampax** [comment] 2020-06-26 15:52
It was as good as it gets. The problem is that it's trying to contact a DBus name very early during initialization, and crashing because it's not found.
As you're running in elementary, that's likely to be org.gnome.Shell (although the log is unclear).

Running outside of GNOME will give you limited functionality (we need a shell extension for certain operations), but it shouldn't outright crash. This is a bug that needs to be fixed on our end.

**Comment by LongJohn-Silver** [comment] 2020-06-26 22:30
> It was as good as it gets. The problem is that it's trying to contact a DBus name very early during initialization, and crashing because it's not found.
> As you're running in elementary, that's likely to be org.gnome.Shell (although the log is unclear).
> 
> Running outside of GNOME will give you limited functionality (we need a shell extension for certain operations), but it shouldn't outright crash. This is a bug that needs to be fixed on our end.

Okay, I can try running it again if something is fixed. Thanks for the great project!

**Comment by sethasaurus** [comment] 2020-06-28 19:30
Got the same problem here. I'm running Linux Mint 19.

Jun 28 20:24:53 animus edu.stanford.Almond.BackgroundService[2262]: ThingEngine-GNOME starting up...
Jun 28 20:24:53 animus edu.stanford.Almond.BackgroundService[2262]: Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined
Jun 28 20:24:54 animus edu.stanford.Almond.BackgroundService[2262]: /app/lib/edu.stanford.Almond/service/main.js:13
Jun 28 20:24:54 animus edu.stanford.Almond.BackgroundService[2262]: process.on('unhandledRejection', (up) => { throw up; });
Jun 28 20:24:54 animus edu.stanford.Almond.BackgroundService[2262]:                                            ^
Jun 28 20:24:54 animus edu.stanford.Almond.BackgroundService[2262]: The name org.gnome.Shell was not provided by any .service files
Jun 28 20:24:54 animus dbus-daemon[2262]: [session uid=1000 pid=2262] Activated service 'edu.stanford.Almond.BackgroundService' failed: Process edu.stanford.Almond.BackgroundService exited with status 1

**Comment by gcampax** [comment] 2020-06-30 03:50
Your first log is clearly caused by the lack of gnome-shell running ("The name org.gnome.Shell was not provided by any .service files")

The second error is less clear. In any case, it points to the background service crashing. You can find the logs for the background service in the journal (as in your first log), or you can run the background service manually with:
```
flatpak run --command=/app/bin/node edu.stanford.Almond /app/lib/edu.stanford.Almond/service/main.js
```
If the background service proceeds all the way to "Engine running", it started correctly.

**Comment by sethasaurus** [comment] 2020-06-30 17:14
OK I did that. Still drops out with an error

seth@animus:~$ flatpak run --command=/app/bin/node edu.stanford.Almond /app/lib/edu.stanford.Almond/service/main.js
ThingEngine-GNOME starting up...
Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined

/app/lib/edu.stanford.Almond/service/main.js:13
process.on('unhandledRejection', (up) => { throw up; });
                                           ^
The name org.gnome.Shell was not provided by any .service files

**Comment by gcampax** [comment] 2020-06-30 17:17
You said you installed GNOME, but are you running it? If not, yeah you'll encounter the same error, until Almond is fixed.

**Comment by sethasaurus** [comment] 2020-06-30 17:25
Yeah I just switched to gnome and it's running. Kinda didn't want to, though..

**Comment by gcampax** [comment] 2020-06-30 17:26
Yeah it should not be required. We'll fix this.

**Comment by sethasaurus** [comment] 2020-06-30 17:55
Seems to work fine under gnome. It's not hearing me via mic but that is more a symptom of my sound setup.

The literal voice translation is funny (e.g. saying "em slash ess" for m/s, or "wined" instead of "wind" for wind speed ) but I realise that's just interpretation.
Maybe some kind of context translation for TTS could be a feature (a lookup table or something).

**Closed** 2020-07-06 01:26 UTC
Labels: bug

**Comment by gcampax** [comment] 2020-07-06 01:28
Alright, Almond now should run outside of GNOME (I tested in elementary). Please wait about one hour for the new build, then grab it from https://flatpak.almond.stanford.edu/ if you wish to test this.

**Comment by sethasaurus** [comment] 2020-07-07 00:37
Works fine now without gnome. Thanks :)
